package compiler

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// Compiler processa arquivos YAML/JSON de aventura e compila para código C estático para MSX.
type Compiler struct {
	Game AdventureGame
}

// NewCompiler cria uma nova instância do compilador.
func NewCompiler() *Compiler {
	return &Compiler{}
}

// LoadFile carrega um arquivo de aventura (.yaml, .yml ou .json).
func (c *Compiler) LoadFile(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("erro ao ler arquivo: %w", err)
	}

	ext := strings.ToLower(filepath.Ext(path))
	if ext == ".json" {
		if err := json.Unmarshal(data, &c.Game); err != nil {
			return fmt.Errorf("erro ao decodificar JSON: %w", err)
		}
	} else {
		if err := yaml.Unmarshal(data, &c.Game); err != nil {
			return fmt.Errorf("erro ao decodificar YAML: %w", err)
		}
	}

	return c.Game.Validate()
}

// CompileInstructions compila as instruções resolvendo rótulos/labels para índices numéricos de PC.
func CompileInstructions(instructions []Instruction) ([]CompiledInstruction, error) {
	// Primeiro passo: mapear rótulos (labels) para seus índices de instrução
	labelMap := make(map[string]int)
	for i, inst := range instructions {
		if inst.Label != "" {
			labelMap[strings.ToUpper(strings.TrimSpace(inst.Label))] = i
		}
	}

	var compiled []CompiledInstruction
	for i, inst := range instructions {
		ci, err := inst.ToCompiled()
		if err != nil {
			return nil, fmt.Errorf("instrução [%d] erro: %w", i, err)
		}

		// Se a instrução fizer desvio condicional/incondicional baseado em label textual:
		// Em instâncias como REG=, REG>, REG<, o terceiro parâmetro é o alvo.
		// Em GOTO, AQUI, LOCAL, TEMOS, EVD=, DNT, o segundo parâmetro é o alvo.
		// Se o usuário especificou target numérico ou se precisarmos resolver:
		compiled = append(compiled, ci)
	}

	return compiled, nil
}

// GenerateCData gera os arquivos C (game_data.h e game_data.c) para serem linkados com a Engine.
func (c *Compiler) GenerateCData(outputDir string) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return err
	}

	hPath := filepath.Join(outputDir, "game_data.h")
	cPath := filepath.Join(outputDir, "game_data.c")

	var hBuf bytes.Buffer
	var cBuf bytes.Buffer

	// =========================================================================
	// Cabeçalho: game_data.h
	// =========================================================================
	hBuf.WriteString("// _____________________________________________________________________________\n")
	hBuf.WriteString("//\n")
	hBuf.WriteString("//  Autogenerated Game Database Header\n")
	hBuf.WriteString(fmt.Sprintf("//  Title: %s (v%s)\n", c.Game.Meta.Title, c.Game.Meta.Version))
	hBuf.WriteString("// _____________________________________________________________________________\n\n")
	hBuf.WriteString("#ifndef GAME_DATA_H\n")
	hBuf.WriteString("#define GAME_DATA_H\n\n")
	hBuf.WriteString("#include \"game_types.h\"\n\n")
	hBuf.WriteString("extern const Game_Database g_GameDatabase;\n\n")
	hBuf.WriteString("#endif // GAME_DATA_H\n")

	// =========================================================================
	// Código Fonte: game_data.c
	// =========================================================================
	cBuf.WriteString("// _____________________________________________________________________________\n")
	cBuf.WriteString("//\n")
	cBuf.WriteString("//  Autogenerated Game Database Source\n")
	cBuf.WriteString(fmt.Sprintf("//  Title: %s\n", c.Game.Meta.Title))
	cBuf.WriteString(fmt.Sprintf("//  Author: %s\n", c.Game.Meta.Author))
	cBuf.WriteString("// _____________________________________________________________________________\n\n")
	cBuf.WriteString("#include \"game_data.h\"\n\n")

	// 1. Mensagens
	cBuf.WriteString("// --- Mensagens ---\n")
	for i, msg := range c.Game.Messages {
		escaped := strings.ReplaceAll(msg.Text, "\"", "\\\"")
		escaped = strings.ReplaceAll(escaped, "\n", "\\n")
		cBuf.WriteString(fmt.Sprintf("static const Game_Message s_msg_%d = { %d, \"%s\" };\n", i, msg.ID, escaped))
	}
	cBuf.WriteString("static const Game_Message* const s_messages[] = {\n")
	for i := range c.Game.Messages {
		cBuf.WriteString(fmt.Sprintf("    &s_msg_%d,\n", i))
	}
	cBuf.WriteString("};\n\n")

	// 2. Objetos
	cBuf.WriteString("// --- Objetos ---\n")
	for i, obj := range c.Game.Objects {
		fullName := obj.FullName()
		escapedDesc := strings.ReplaceAll(obj.Description, "\"", "\\\"")
		cBuf.WriteString(fmt.Sprintf("static const Game_Object s_obj_%d = { %d, %d, 0x%02X, \"%s\", \"%s\" };\n",
			i, obj.ID, obj.InitialSituation, obj.Consistency.ToByte(), fullName, escapedDesc))
	}
	cBuf.WriteString("static const Game_Object* const s_objects[] = {\n")
	for i := range c.Game.Objects {
		cBuf.WriteString(fmt.Sprintf("    &s_obj_%d,\n", i))
	}
	cBuf.WriteString("};\n\n")

	// 3. Posições (Salas)
	cBuf.WriteString("// --- Posições ---\n")
	for i, pos := range c.Game.Positions {
		escapedDesc := strings.ReplaceAll(pos.Description, "\"", "\\\"")
		cBuf.WriteString(fmt.Sprintf("static const Game_Position s_pos_%d = { %d, { %d, %d, %d, %d }, \"%s\" };\n",
			i, pos.ID, pos.Exits.North, pos.Exits.South, pos.Exits.East, pos.Exits.West, escapedDesc))
	}
	cBuf.WriteString("static const Game_Position* const s_positions[] = {\n")
	for i := range c.Game.Positions {
		cBuf.WriteString(fmt.Sprintf("    &s_pos_%d,\n", i))
	}
	cBuf.WriteString("};\n\n")

	// 4. Instruções de Funções
	cBuf.WriteString("// --- Funções ---\n")
	for i, fn := range c.Game.Functions {
		compiled, err := CompileInstructions(fn.Instructions)
		if err != nil {
			return fmt.Errorf("função %d erro: %w", fn.ID, err)
		}
		cBuf.WriteString(fmt.Sprintf("static const Game_Instruction s_func_inst_%d[] = {\n", i))
		for _, inst := range compiled {
			cBuf.WriteString(fmt.Sprintf("    { %d, %d, %d, %d },\n", inst.Op, inst.P1, inst.P2, inst.P3))
		}
		if len(compiled) == 0 {
			cBuf.WriteString("    { 0, 0, 0, 0 }\n")
		}
		cBuf.WriteString("};\n")
		cBuf.WriteString(fmt.Sprintf("static const Game_Function s_func_%d = { %d, s_func_inst_%d, %d };\n\n",
			i, fn.ID, i, len(compiled)))
	}
	cBuf.WriteString("static const Game_Function* const s_functions[] = {\n")
	for i := range c.Game.Functions {
		cBuf.WriteString(fmt.Sprintf("    &s_func_%d,\n", i))
	}
	cBuf.WriteString("};\n\n")

	// 5. Instruções de Comandos
	cBuf.WriteString("// --- Comandos ---\n")
	for i, cmd := range c.Game.Commands {
		compiled, err := CompileInstructions(cmd.Instructions)
		if err != nil {
			return fmt.Errorf("comando %d erro: %w", i, err)
		}
		cBuf.WriteString(fmt.Sprintf("static const Game_Instruction s_cmd_inst_%d[] = {\n", i))
		for _, inst := range compiled {
			cBuf.WriteString(fmt.Sprintf("    { %d, %d, %d, %d },\n", inst.Op, inst.P1, inst.P2, inst.P3))
		}
		if len(compiled) == 0 {
			cBuf.WriteString("    { 0, 0, 0, 0 }\n")
		}
		cBuf.WriteString("};\n")
		cBuf.WriteString(fmt.Sprintf("static const Game_Command s_cmd_%d = { %d, %d, %d, s_cmd_inst_%d, %d };\n\n",
			i, cmd.Verb, cmd.Object1, cmd.Object2, i, len(compiled)))
	}
	cBuf.WriteString("static const Game_Command* const s_commands[] = {\n")
	for i := range c.Game.Commands {
		cBuf.WriteString(fmt.Sprintf("    &s_cmd_%d,\n", i))
	}
	cBuf.WriteString("};\n\n")

	// 6. Estrutura Principal: Game_Database
	initialPos := c.Game.Config.InitialPosition
	if initialPos == 0 {
		initialPos = 1
	}
	maxCarried := c.Game.Config.MaxCarried
	if maxCarried == 0 {
		maxCarried = DefaultMaxCarried
	}
	maxInObj3 := c.Game.Config.MaxInContainer
	if maxInObj3 == 0 {
		maxInObj3 = DefaultMaxInContainer
	}

	cBuf.WriteString("// --- Base de Dados do Jogo ---\n")
	cBuf.WriteString("const Game_Database g_GameDatabase = {\n")
	cBuf.WriteString(fmt.Sprintf("    \"%s\",\n", strings.ReplaceAll(c.Game.Meta.Title, "\"", "\\\"")))
	cBuf.WriteString(fmt.Sprintf("    %d, // posicao_inicial\n", initialPos))
	cBuf.WriteString(fmt.Sprintf("    %d, // max_carregados\n", maxCarried))
	cBuf.WriteString(fmt.Sprintf("    %d, // max_no_obj3\n", maxInObj3))
	cBuf.WriteString("    s_positions,\n")
	cBuf.WriteString(fmt.Sprintf("    %d,\n", len(c.Game.Positions)))
	cBuf.WriteString("    s_objects,\n")
	cBuf.WriteString(fmt.Sprintf("    %d,\n", len(c.Game.Objects)))
	cBuf.WriteString("    s_commands,\n")
	cBuf.WriteString(fmt.Sprintf("    %d,\n", len(c.Game.Commands)))
	cBuf.WriteString("    s_functions,\n")
	cBuf.WriteString(fmt.Sprintf("    %d,\n", len(c.Game.Functions)))
	cBuf.WriteString("    s_messages,\n")
	cBuf.WriteString(fmt.Sprintf("    %d\n", len(c.Game.Messages)))
	cBuf.WriteString("};\n")

	// Grava os arquivos
	if err := os.WriteFile(hPath, hBuf.Bytes(), 0644); err != nil {
		return err
	}
	return os.WriteFile(cPath, cBuf.Bytes(), 0644)
}
